import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:intl/intl.dart';

import '../../blocs/auth/auth_bloc.dart';
import '../../blocs/schedule_suggestions/schedule_suggestions_bloc.dart';
import '../../core/di.dart';
import '../../core/router/app_routes.dart';
import '../../core/theme/app_colors.dart';
import '../../core/theme/app_spacing.dart';
import '../../core/theme/app_text_styles.dart';
import '../../data/models/schedule_suggestion.dart';
import '../../widgets/app_bottom_nav_bar.dart';
import '../../widgets/app_card.dart';
import '../../widgets/app_header.dart';
import '../../widgets/empty_view.dart';
import '../../widgets/error_view.dart';
import '../../widgets/loading_view.dart';
import '../../widgets/primary_button.dart';
import '../../widgets/status_badge.dart';

/// Coordinator's Delay Suggestions inbox — surfaces every pending
/// schedule adjustment generated by delayed surgeries.
class ScheduleSuggestionsScreen extends StatelessWidget {
  const ScheduleSuggestionsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) => ScheduleSuggestionsBloc(
        service: context.read<AppContainer>().scheduleSuggestionService,
      )..add(const ScheduleSuggestionsRequested()),
      child: const _View(),
    );
  }
}

class _View extends StatelessWidget {
  const _View();

  @override
  Widget build(BuildContext context) {
    final user = context.read<AuthBloc>().state.user;
    if (user == null) return const SizedBox.shrink();

    return Scaffold(
      appBar: const AppHeader(subtitle: 'Delay Suggestions'),
      bottomNavigationBar: AppBottomNavBar(
        role: user.role,
        currentRouteName: AppRoutes.coordinatorSuggestions,
      ),
      body: SafeArea(
        top: false,
        child: BlocConsumer<ScheduleSuggestionsBloc,
            ScheduleSuggestionsState>(
          listenWhen: (p, c) =>
              p.actionError != c.actionError && c.actionError != null,
          listener: (context, state) {
            ScaffoldMessenger.of(context)
              ..clearSnackBars()
              ..showSnackBar(SnackBar(content: Text(state.actionError!)));
          },
          builder: (context, state) {
            return switch (state.status) {
              ScheduleSuggestionsStatus.initial ||
              ScheduleSuggestionsStatus.loading =>
                state.items.isEmpty ? const LoadingView() : _List(state: state),
              ScheduleSuggestionsStatus.error => ErrorView(
                  message:
                      state.errorMessage ?? 'Failed to load suggestions',
                  onRetry: () => context
                      .read<ScheduleSuggestionsBloc>()
                      .add(const ScheduleSuggestionsRequested()),
                ),
              ScheduleSuggestionsStatus.loaded => _List(state: state),
            };
          },
        ),
      ),
    );
  }
}

class _List extends StatelessWidget {
  const _List({required this.state});

  final ScheduleSuggestionsState state;

  @override
  Widget build(BuildContext context) {
    final pending = state.items.pendingOnly();

    return RefreshIndicator(
      color: AppColors.primary,
      onRefresh: () async => context
          .read<ScheduleSuggestionsBloc>()
          .add(const ScheduleSuggestionsRefreshRequested()),
      child: CustomScrollView(
        physics: const AlwaysScrollableScrollPhysics(),
        slivers: [
          SliverPadding(
            padding: const EdgeInsets.fromLTRB(
              AppSpacing.screenEdge,
              AppSpacing.md,
              AppSpacing.screenEdge,
              AppSpacing.xs,
            ),
            sliver: SliverToBoxAdapter(
              child: Row(
                children: [
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text('Delay Resolution',
                            style: AppTextStyles.headlineMd),
                        Text(
                          pending.isEmpty
                              ? 'No pending adjustments'
                              : '${pending.length} pending adjustment${pending.length == 1 ? '' : 's'}',
                          style: AppTextStyles.bodySm,
                        ),
                      ],
                    ),
                  ),
                  if (pending.isNotEmpty)
                    Container(
                      padding: const EdgeInsets.symmetric(
                        horizontal: AppSpacing.sm,
                        vertical: AppSpacing.xxs + 2,
                      ),
                      decoration: BoxDecoration(
                        color: AppColors.statusPreparingBg,
                        borderRadius:
                            BorderRadius.circular(AppSpacing.radiusPill),
                        border: Border.all(
                          color: AppColors.statusPreparingBorder,
                        ),
                      ),
                      child: Row(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          Container(
                            width: 8,
                            height: 8,
                            decoration: BoxDecoration(
                              color: AppColors.accentText,
                              shape: BoxShape.circle,
                            ),
                          ),
                          const SizedBox(width: AppSpacing.xs),
                          Text(
                            'ACTIVE OVERRUN',
                            style: AppTextStyles.labelSm.copyWith(
                              color: AppColors.accentText,
                              letterSpacing: 0.6,
                            ),
                          ),
                        ],
                      ),
                    ),
                ],
              ),
            ),
          ),
          if (pending.isEmpty)
            const SliverFillRemaining(
              hasScrollBody: false,
              child: EmptyView(
                icon: Icons.inbox_outlined,
                title: 'No pending suggestions',
                subtitle: 'You\'re all caught up.',
              ),
            )
          else
            SliverPadding(
              padding: const EdgeInsets.symmetric(
                horizontal: AppSpacing.screenEdge,
              ),
              sliver: SliverList.separated(
                itemCount: pending.length,
                separatorBuilder: (_, __) =>
                    const SizedBox(height: AppSpacing.md),
                itemBuilder: (context, i) => _SuggestionCard(
                  suggestion: pending[i],
                  isBusy: state.actionInFlightId == pending[i].id,
                ),
              ),
            ),
          const SliverToBoxAdapter(child: SizedBox(height: AppSpacing.lg)),
        ],
      ),
    );
  }
}

class _SuggestionCard extends StatelessWidget {
  const _SuggestionCard({required this.suggestion, required this.isBusy});

  final ScheduleSuggestion suggestion;
  final bool isBusy;

  static final _fmt = DateFormat('EEE, MMM d · h:mm a');

  @override
  Widget build(BuildContext context) {
    final surgery = suggestion.surgery;
    final room = suggestion.suggestedRoom;
    return AppCard(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Expanded(
                child: Text(
                  surgery?.patient?.name ??
                      'Surgery #${suggestion.surgeryId}',
                  style: AppTextStyles.titleLg,
                ),
              ),
              StatusBadge.suggestion(suggestion.status),
            ],
          ),
          const SizedBox(height: AppSpacing.xs),
          _Row(
            icon: Icons.meeting_room_outlined,
            text: room?.name ?? 'Room #${suggestion.suggestedRoomId}',
          ),
          _Row(
            icon: Icons.event,
            text: _fmt.format(suggestion.suggestedStart.toLocal()),
          ),
          const SizedBox(height: AppSpacing.xs),
          Container(
            padding: const EdgeInsets.all(AppSpacing.xs),
            decoration: BoxDecoration(
              color: AppColors.background,
              borderRadius: BorderRadius.circular(AppSpacing.radiusSmall),
            ),
            child: Text(suggestion.reason, style: AppTextStyles.bodySm),
          ),
          const SizedBox(height: AppSpacing.md),
          Row(
            children: [
              Expanded(
                child: PrimaryButton(
                  label: 'Accept',
                  icon: Icons.check,
                  isLoading: isBusy,
                  onPressed: () => context
                      .read<ScheduleSuggestionsBloc>()
                      .add(ScheduleSuggestionAcceptRequested(suggestion.id)),
                ),
              ),
              const SizedBox(width: AppSpacing.sm),
              Expanded(
                child: PrimaryButton(
                  label: 'Reject',
                  icon: Icons.close,
                  variant: PrimaryButtonVariant.subdued,
                  onPressed: isBusy
                      ? null
                      : () => context
                          .read<ScheduleSuggestionsBloc>()
                          .add(ScheduleSuggestionRejectRequested(
                              suggestion.id)),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

class _Row extends StatelessWidget {
  const _Row({required this.icon, required this.text});

  final IconData icon;
  final String text;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: AppSpacing.xxs),
      child: Row(
        children: [
          Icon(icon, size: 16, color: AppColors.textSecondary),
          const SizedBox(width: AppSpacing.xs),
          Expanded(child: Text(text, style: AppTextStyles.bodyMd)),
        ],
      ),
    );
  }
}
