import 'package:equatable/equatable.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

import '../../core/error/exceptions.dart';
import '../../data/models/schedule_suggestion.dart';
import '../../data/models/schedule_suggestion_status.dart';
import '../../data/services/schedule_suggestion_service.dart';

part 'schedule_suggestions_event.dart';
part 'schedule_suggestions_state.dart';

/// Owns the "Delay Suggestions" screen — the coordinator's inbox of
/// pending schedule adjustments generated by delayed surgeries.
///
/// Every accept/reject action affects a single suggestion, so the Bloc
/// tracks a per-item "action-in-flight" id to disable that specific card
/// without freezing the whole list.
class ScheduleSuggestionsBloc
    extends Bloc<ScheduleSuggestionsEvent, ScheduleSuggestionsState> {
  ScheduleSuggestionsBloc({
    required ScheduleSuggestionService service,
  })  : _service = service,
        super(const ScheduleSuggestionsState.initial()) {
    on<ScheduleSuggestionsRequested>(_onRequested);
    on<ScheduleSuggestionsRefreshRequested>(_onRefresh);
    on<ScheduleSuggestionAcceptRequested>(_onAccept);
    on<ScheduleSuggestionRejectRequested>(_onReject);
  }

  final ScheduleSuggestionService _service;

  Future<void> _onRequested(
    ScheduleSuggestionsRequested event,
    Emitter<ScheduleSuggestionsState> emit,
  ) async {
    emit(state.copyWith(status: ScheduleSuggestionsStatus.loading));
    await _load(emit);
  }

  Future<void> _onRefresh(
    ScheduleSuggestionsRefreshRequested event,
    Emitter<ScheduleSuggestionsState> emit,
  ) async {
    // Silent refresh — see room_timeline_bloc for the reasoning.
    await _load(emit);
  }

  Future<void> _load(Emitter<ScheduleSuggestionsState> emit) async {
    try {
      final items = await _service.list();
      emit(state.copyWith(
        status: ScheduleSuggestionsStatus.loaded,
        items: items,
        clearError: true,
      ));
    } on ApiException catch (e) {
      emit(state.copyWith(
        status: ScheduleSuggestionsStatus.error,
        errorMessage: e.message,
        errorCode: e.errorCode,
      ));
    }
  }

  Future<void> _onAccept(
    ScheduleSuggestionAcceptRequested event,
    Emitter<ScheduleSuggestionsState> emit,
  ) async {
    emit(state.copyWith(actionInFlightId: event.id));
    try {
      final updated = await _service.accept(event.id);
      _replace(updated, emit);
    } on ApiException catch (e) {
      emit(state.copyWith(
        actionError: e.message,
        actionErrorCode: e.errorCode,
        clearActionInFlightId: true,
      ));
    }
  }

  Future<void> _onReject(
    ScheduleSuggestionRejectRequested event,
    Emitter<ScheduleSuggestionsState> emit,
  ) async {
    emit(state.copyWith(actionInFlightId: event.id));
    try {
      final updated = await _service.reject(event.id);
      _replace(updated, emit);
    } on ApiException catch (e) {
      emit(state.copyWith(
        actionError: e.message,
        actionErrorCode: e.errorCode,
        clearActionInFlightId: true,
      ));
    }
  }

  /// Replaces the mutated item in-place. Accepting one suggestion
  /// server-side auto-rejects sibling suggestions for the same surgery,
  /// so a full reload is safer than trusting local state. We fire it
  /// without awaiting so the UI reflects the accept immediately.
  void _replace(
    ScheduleSuggestion updated,
    Emitter<ScheduleSuggestionsState> emit,
  ) {
    final next = [
      for (final s in state.items) s.id == updated.id ? updated : s,
    ];
    emit(state.copyWith(
      items: next,
      clearActionInFlightId: true,
      clearActionError: true,
    ));
    add(const ScheduleSuggestionsRefreshRequested());
  }
}

/// Convenience filter used by the screen.
extension PendingFilter on List<ScheduleSuggestion> {
  List<ScheduleSuggestion> pendingOnly() =>
      where((s) => s.status == ScheduleSuggestionStatus.pending).toList();
}
